import type { Metadata } from 'next';
import Link from 'next/link';
import styles from '../legal.module.css';

export const metadata: Metadata = {
    title: 'Terms of Service — Cura3.ai',
    description: 'Terms and conditions for using the Cura3.ai AI medical diagnostics platform.',
};

export default function TermsPage() {
    return (
        <div className={styles.legalPage}>
            <Link href="/" className={styles.backLink}>← Back to Home</Link>

            <div className={styles.legalHeader}>
                <h1>Terms of Service</h1>
                <p>Last updated: February 25, 2026</p>
            </div>

            <div className={styles.section}>
                <h2>1. Acceptance of Terms</h2>
                <p>
                    By accessing and using Cura3.ai (&ldquo;the Platform&rdquo;), you agree to be bound by these Terms of
                    Service. If you do not agree, please do not use the Platform.
                </p>
            </div>

            <div className={styles.section}>
                <h2>2. Description of Service</h2>
                <p>
                    Cura3.ai provides AI-powered medical report analysis for <strong>research and educational
                        purposes only</strong>. The Platform uses multiple AI specialist agents to analyze medical
                    reports and generate diagnostic insights.
                </p>
            </div>

            <div className={styles.section}>
                <h2>3. Medical Disclaimer</h2>
                <div className={styles.highlight}>
                    <p>
                        Cura3.ai is NOT a medical device and is NOT intended to be used for clinical decision-making.
                        All outputs are generated by artificial intelligence and must NOT be used as a substitute for
                        professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare
                        provider for any health-related decisions.
                    </p>
                </div>
            </div>

            <div className={styles.section}>
                <h2>4. User Accounts</h2>
                <ul>
                    <li>You must authenticate via Google Sign-In to use the Platform.</li>
                    <li>You are responsible for maintaining the security of your account.</li>
                    <li>You must provide accurate and complete information.</li>
                    <li>You must be at least 18 years old to create an account.</li>
                </ul>
            </div>

            <div className={styles.section}>
                <h2>5. Data & Privacy</h2>
                <p>
                    Your use of the Platform is also governed by our <Link href="/privacy">Privacy Policy</Link>.
                    You retain ownership of all medical reports you upload. We store data only as needed to
                    provide the Service, and you may delete your data at any time.
                </p>
            </div>

            <div className={styles.section}>
                <h2>6. Acceptable Use</h2>
                <p>You agree not to:</p>
                <ul>
                    <li>Use the Platform for actual clinical diagnostics or medical decision-making.</li>
                    <li>Upload fraudulent or fabricated medical reports.</li>
                    <li>Attempt to gain unauthorized access to other users&apos; data.</li>
                    <li>Use the Platform in any way that could harm or overload our systems.</li>
                </ul>
            </div>

            <div className={styles.section}>
                <h2>7. Limitation of Liability</h2>
                <p>
                    The Platform and its creators bear no responsibility for any actions taken based on AI-generated
                    outputs. Use of the Platform is entirely at your own risk.
                </p>
            </div>

            <div className={styles.section}>
                <h2>8. Changes to Terms</h2>
                <p>
                    We reserve the right to modify these Terms at any time. Continued use of the Platform after
                    changes constitutes acceptance of the revised Terms.
                </p>
            </div>

            <div className={styles.section}>
                <h2>9. Contact</h2>
                <p>
                    For questions about these Terms, please contact us at <strong>support@cura3.ai</strong>.
                </p>
            </div>
        </div>
    );
}
